name: Create Release

on:
  push:
    tags:
      # Matches release/<namespace>/<resource_name>/<semantic_version>
      # (e.g., "release/coder-labs/sourcegraph-amp/v1.0.1")
      - "release/*/*/v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for changelog generation
          persist-credentials: false
      
      - name: Extract tag information
        id: tag_info
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          
          # Extract namespace, module, and version from tag
          # Format: release/namespace/module/version
          IFS='/' read -ra PARTS <<< "$TAG"
          NAMESPACE="${PARTS[1]}"
          MODULE="${PARTS[2]}"
          VERSION="${PARTS[3]}"
          
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
          echo "module=$MODULE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "module_path=registry/$NAMESPACE/modules/$MODULE" >> $GITHUB_OUTPUT
          
          # Create release title
          RELEASE_TITLE="$NAMESPACE/$MODULE $VERSION"
          echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT
      
      - name: Find previous tag
        id: prev_tag
        env:
          NAMESPACE: ${{ steps.tag_info.outputs.namespace }}
          MODULE: ${{ steps.tag_info.outputs.module }}
          CURRENT_TAG: ${{ steps.tag_info.outputs.tag }}
        run: |
          # Find the previous tag for this specific module
          PREV_TAG=$(git tag -l "release/$NAMESPACE/$MODULE/v*" | grep -v "$CURRENT_TAG" | sort -V | tail -1)
          
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, using initial commit"
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "Previous tag: $PREV_TAG"
      
      - name: Generate changelog
        id: changelog
        env:
          NAMESPACE: ${{ steps.tag_info.outputs.namespace }}
          MODULE: ${{ steps.tag_info.outputs.module }}
          MODULE_PATH: ${{ steps.tag_info.outputs.module_path }}
          PREV_TAG: ${{ steps.prev_tag.outputs.prev_tag }}
          CURRENT_TAG: ${{ steps.tag_info.outputs.tag }}
        run: |
          echo "Generating changelog for $MODULE_PATH between $PREV_TAG and $CURRENT_TAG"
          
          # Get commits that affected the specific module path
          COMMITS=$(git log --oneline --no-merges "$PREV_TAG..$CURRENT_TAG" -- "$MODULE_PATH" | cut -d' ' -f1)
          
          if [ -z "$COMMITS" ]; then
            echo "No commits found for this module"
            echo "changelog=No changes found for this module." >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Generate changelog from commits
          CHANGELOG="## What's Changed\n\n"
          
          for commit in $COMMITS; do
            # Get commit message
            COMMIT_MSG=$(git log --format="%s" -n 1 $commit)
            
            # Extract PR number from commit message (handles various formats)
            PR_NUM=$(echo "$COMMIT_MSG" | grep -oE '\(#[0-9]+\)|#[0-9]+' | grep -oE '[0-9]+' | head -1 || echo "")
            
            # Get GitHub username from commit (try multiple methods)
            # First try to get from commit trailer
            GH_USER=$(git log --format="%(trailers:key=Co-authored-by,valueonly)" -n 1 $commit | head -1 | grep -oE '@[^>]+' | cut -d'@' -f2 | cut -d'.' -f1 || echo "")
            
            # If no co-author, try to extract from email
            if [ -z "$GH_USER" ]; then
              EMAIL=$(git log --format="%ae" -n 1 $commit)
              if [[ "$EMAIL" == *"@users.noreply.github.com" ]]; then
                GH_USER=$(echo "$EMAIL" | cut -d'@' -f1 | sed 's/^[0-9]*+//')
              else
                GH_USER=$(echo "$EMAIL" | cut -d'@' -f1)
              fi
            fi
            
            # Fallback to commit author name if no GitHub username found
            if [ -z "$GH_USER" ]; then
              GH_USER=$(git log --format="%an" -n 1 $commit | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
            fi
            
            # Format changelog entry
            if [ -n "$PR_NUM" ]; then
              CHANGELOG="${CHANGELOG}* $COMMIT_MSG by @$GH_USER in https://github.com/coder/registry/pull/$PR_NUM\n"
            else
              CHANGELOG="${CHANGELOG}* $COMMIT_MSG by @$GH_USER\n"
            fi
          done
          
          # Add full changelog link
          CHANGELOG="${CHANGELOG}\n\n**Full Changelog**: https://github.com/coder/registry/compare/$PREV_TAG...$CURRENT_TAG"
          
          # Save changelog to output (escape newlines for GitHub Actions)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo -e "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.tag_info.outputs.tag }}
          RELEASE_TITLE: ${{ steps.tag_info.outputs.release_title }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        run: |
          gh release create "$TAG_NAME" \
            --title "$RELEASE_TITLE" \
            --notes "$CHANGELOG"