name: Version Check

on:
  pull_request:
    paths:
      - 'registry/**/modules/**'

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if module versions need updating
        run: |
          echo "🔍 Checking if module versions need to be updated..."
          
          # Run the version bump script in dry-run mode to see what would change
          if ./.github/scripts/version-bump.sh patch origin/main; then
            echo "✅ Module versions are up to date or no modules were modified"
          else
            echo "❌ Module versions may need to be updated"
            echo ""
            echo "To update module versions, run one of:"
            echo "  ./.github/scripts/version-bump.sh patch"
            echo "  ./.github/scripts/version-bump.sh minor"
            echo "  ./.github/scripts/version-bump.sh major"
            echo ""
            echo "Or add a version label to this PR: version:patch, version:minor, or version:major"
            exit 1
          fi